//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFO1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airlines_Arrivals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Airlines_Arrivals()
        {
            this.ArrivalTimeTables = new HashSet<ArrivalTimeTable>();
        }
    
        public int AirID { get; set; }
        public string Airline { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArrivalTimeTable> ArrivalTimeTables { get; set; }
    }
}
